setwd("~/Documents/7thSemester/dmp/corpus")
library("RSQLite")
library("tokenizers")
library("dplyr")
library("textclean")
library("stringr")
library("tm")
library(qdap)
# library(rJava)
# library("openNLPdata")

stock <- c("Title", "Type", "ID", "Unit")
dali <- scan("rawTexts/virginia-woolf-mrs-dalloway.txt",what="character",sep="\n")
dali.start <-which(dali == "Mrs. Dalloway said she would buy the flowers herself.")
dali.end <- which(dali == "For there she was.")